version: '3.7'
services:
  database:
    container_name: "discounts_db"
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-ds:/var/lib/postgresql/data

volumes:
  db-ds: